require("config.options")
require("config.mappings")
require("config.autocmds")
require("config.lazy")

vim.cmd("colorscheme gruvbox")
vim.cmd("highlight Normal guibg=none")
vim.cmd("highlight NonText guibg=none")
vim.cmd("highlight Normal ctermbg=none")
vim.cmd("highlight NonText ctermbg=none")
